import GDLowerBound.Schedule.Chain
import GDLowerBound.Schedule.Functional
import GDLowerBound.Geometry.ProjectionEnvelope
import GDLowerBound.Optimization.SmoothConvex
import Mathlib.Analysis.Convex.Topology
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Tactic

/-!
# Geometric realization of chronological chains

This file supplies the finite-dimensional geometry used to turn a chronological chain into one
smooth convex objective.  The generic convex-hull reduction is separated from the schedule
scalars and block vectors so that the projection calculation can be checked generator by
generator.
-/

open scoped InnerProductSpace BigOperators
open Set

namespace GDLowerBound.GeometricRealization

section GeneratorHull

variable {E ι : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- The origin together with a finite family of proposed gradients. -/
def generatorSet (g : ι → E) : Set E := insert 0 (Set.range g)

/-- The convex hull used by the projection-envelope construction. -/
def generatorHull (g : ι → E) : Set E := convexHull ℝ (generatorSet g)

variable [Finite ι]

omit [InnerProductSpace ℝ E] in
theorem generatorSet_finite (g : ι → E) : (generatorSet g).Finite :=
  (Set.finite_range g).insert 0

theorem generatorHull_compact (g : ι → E) : IsCompact (generatorHull g) :=
  (generatorSet_finite g).isCompact_convexHull ℝ

theorem generatorHull_complete (g : ι → E) : IsComplete (generatorHull g) :=
  (generatorHull_compact g).isComplete

omit [Finite ι] in
theorem generatorHull_convex (g : ι → E) : Convex ℝ (generatorHull g) :=
  convex_convexHull ℝ (generatorSet g)

omit [Finite ι] in
theorem zero_mem_generatorHull (g : ι → E) : 0 ∈ generatorHull g := by
  apply subset_convexHull ℝ
  simp [generatorSet]

omit [Finite ι] in
theorem generator_mem_generatorHull (g : ι → E) (i : ι) : g i ∈ generatorHull g := by
  apply subset_convexHull ℝ
  exact Set.mem_insert_iff.mpr (Or.inr ⟨i, rfl⟩)

variable [CompleteSpace E]

/-- The smooth convex objective generated by the finite gradient family. -/
noncomputable def generatorObjective (g : ι → E) : SmoothConvexFn E 1 where
  toFun := projectionEnvelope (generatorHull g)
    (Set.nonempty_of_mem (zero_mem_generatorHull g))
    (generatorHull_complete g) (generatorHull_convex g)
  grad := convexProj (generatorHull g)
    (Set.nonempty_of_mem (zero_mem_generatorHull g))
    (generatorHull_complete g) (generatorHull_convex g)
  convex := projectionEnvelope_convex _ _ _ _
  hasGradient := hasGradientAt_projectionEnvelope _ _ _ _
  grad_lipschitz := by
    intro x y
    simpa using convexProj_nonexpansive (generatorHull g)
      (Set.nonempty_of_mem (zero_mem_generatorHull g))
      (generatorHull_complete g) (generatorHull_convex g) x y
  minimizer := 0
  minimizes := by
    intro x
    exact (projectionEnvelope_isMinOn_zero (generatorHull g)
      (Set.nonempty_of_mem (zero_mem_generatorHull g))
      (generatorHull_complete g) (generatorHull_convex g)
      (zero_mem_generatorHull g)) (Set.mem_univ x)

omit [CompleteSpace E] in
/-- A linear-functional comparison on the generators extends to their convex hull. -/
theorem inner_le_on_convexHull {S : Set E} {z g₀ : E}
    (hgen : ∀ v ∈ S, ⟪z, v⟫_ℝ ≤ ⟪z, g₀⟫_ℝ) :
    ∀ v ∈ convexHull ℝ S, ⟪z, v⟫_ℝ ≤ ⟪z, g₀⟫_ℝ := by
  intro v hv
  apply (convexHull_min hgen ?_) hv
  exact convex_halfSpace_le (innerSL ℝ z).toLinearMap.isLinear _

omit [CompleteSpace E] in
/-- To prove that a proposed generator is the projection, it suffices to compare the shifted
inner product with zero and with every generator. -/
theorem convexProj_generator_eq (g : ι → E) (i : ι) (x : E)
    (hzero : 0 ≤ ⟪x - g i, g i⟫_ℝ)
    (hother : ∀ j, ⟪x - g i, g j⟫_ℝ ≤ ⟪x - g i, g i⟫_ℝ) :
    convexProj (generatorHull g) (Set.nonempty_of_mem (zero_mem_generatorHull g))
      (generatorHull_complete g) (generatorHull_convex g) x = g i := by
  symm
  apply eq_convexProj_of_mem_of_vi (generatorHull g)
    (Set.nonempty_of_mem (zero_mem_generatorHull g))
    (generatorHull_complete g) (generatorHull_convex g) x (g i)
    (generator_mem_generatorHull g i)
  intro v hv
  have hmax : ⟪x - g i, v⟫_ℝ ≤ ⟪x - g i, g i⟫_ℝ := by
    apply inner_le_on_convexHull (S := generatorSet g)
    · intro w hw
      simp only [generatorSet, Set.mem_insert_iff, Set.mem_range] at hw
      rcases hw with rfl | ⟨j, rfl⟩
      · simpa using hzero
      · exact hother j
    · simpa [generatorHull] using hv
  rw [inner_sub_right]
  linarith

end GeneratorHull

section ChainScalars

open GDLowerBound.Schedule

variable {T : ℕ} {h : StepSchedule T}

/-- The scale `H_i` of a nonterminal block. -/
noncomputable def transitionScale (c : Chain h) (i : Fin c.length) : ℝ :=
  c.gapMass i + excess h (c.selected i)

/-- The scale of the block following transition `i`; at the last transition this is the
terminal scale. -/
noncomputable def nextScale (c : Chain h) (i : Fin c.length) : ℝ :=
  if hi : i.val + 1 < c.length then
    transitionScale c ⟨i.val + 1, hi⟩
  else
    c.terminalScale

theorem transitionScale_pos (c : Chain h) (hh : IsNonnegativeSchedule h)
    (i : Fin c.length) : 0 < transitionScale c i := by
  have hU := c.gapMass_pos hh i
  have hy := c.selected_excess_pos i
  simp only [transitionScale]
  linarith

theorem nextScale_pos (c : Chain h) (hh : IsNonnegativeSchedule h)
    (i : Fin c.length) : 0 < nextScale c i := by
  simp only [nextScale]
  split_ifs with hi
  · exact transitionScale_pos c hh ⟨i.val + 1, hi⟩
  · exact c.terminalScale_pos hh

/-- The local upper bound `χ_i` for the squared amplitude ratio. -/
noncomputable def localAmplitudeBound (c : Chain h) (i : Fin c.length) : ℝ :=
  excess h (c.selected i) * nextScale c i /
    (c.gapMass i * (transitionScale c i + nextScale c i))

theorem localAmplitudeBound_pos (c : Chain h) (hh : IsNonnegativeSchedule h)
    (i : Fin c.length) : 0 < localAmplitudeBound c i := by
  have hy := c.selected_excess_pos i
  have hnext := nextScale_pos c hh i
  have hU := c.gapMass_pos hh i
  have hH := transitionScale_pos c hh i
  simp only [localAmplitudeBound]
  positivity

/-- Positivity and the local comparison bound required of the amplitudes. -/
def AmplitudesAdmissible (c : Chain h) (γ : Fin c.length → ℝ) : Prop :=
  (∀ i, 0 < γ i) ∧ (∀ i, γ i ^ 2 ≤ localAmplitudeBound c i)

/-- A totalized amplitude used only to define finite prefix products. -/
noncomputable def amplitudeNat (c : Chain h) (γ : Fin c.length → ℝ) (j : ℕ) : ℝ :=
  if hj : j < c.length then γ ⟨j, hj⟩ else 1

/-- The coordinate amplitude `λ_i = ∏_{j<i} γ_j`. -/
noncomputable def coordinateAmplitude (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin (c.length + 1)) : ℝ :=
  ∏ j ∈ Finset.range i.val, amplitudeNat c γ j

@[simp]
theorem coordinateAmplitude_zero (c : Chain h) (γ : Fin c.length → ℝ) :
    coordinateAmplitude c γ 0 = 1 := by
  simp [coordinateAmplitude]

theorem coordinateAmplitude_succ (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) :
    coordinateAmplitude c γ i.succ = coordinateAmplitude c γ i.castSucc * γ i := by
  simp [coordinateAmplitude, Finset.prod_range_succ, amplitudeNat, i.isLt]

theorem coordinateAmplitude_pos (c : Chain h) (γ : Fin c.length → ℝ)
    (hγ : ∀ i, 0 < γ i) (i : Fin (c.length + 1)) :
    0 < coordinateAmplitude c γ i := by
  apply Finset.prod_pos
  intro j hj
  simp only [Finset.mem_range] at hj
  simp [amplitudeNat, lt_of_lt_of_le hj (Nat.le_of_lt_succ i.isLt), hγ]

/-- The Euclidean space with one coordinate per block. -/
abbrev BlockSpace (c : Chain h) := EuclideanSpace ℝ (Fin (c.length + 1))

/-- The canonical orthonormal coordinate vector. -/
noncomputable def axis (c : Chain h) (i : Fin (c.length + 1)) : BlockSpace c :=
  EuclideanSpace.single i 1

/-- The anchor point `X_i = λ_i e_i`. -/
noncomputable def anchor (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin (c.length + 1)) : BlockSpace c :=
  coordinateAmplitude c γ i • axis c i

/-- The gradient attached to a nonterminal block. -/
noncomputable def transitionGradient (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) : BlockSpace c :=
  (coordinateAmplitude c γ i.castSucc / transitionScale c i) •
    (axis c i.castSucc - γ i • axis c i.succ)

/-- The terminal block gradient. -/
noncomputable def terminalGradient (c : Chain h) (γ : Fin c.length → ℝ) :
    BlockSpace c :=
  (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) •
    axis c (Fin.last c.length)

/-- All block gradients, with the terminal gradient stored at the last coordinate. -/
noncomputable def blockGradient (c : Chain h) (γ : Fin c.length → ℝ) :
    Fin (c.length + 1) → BlockSpace c :=
  Fin.lastCases (terminalGradient c γ) (transitionGradient c γ)

@[simp]
theorem blockGradient_last (c : Chain h) (γ : Fin c.length → ℝ) :
    blockGradient c γ (Fin.last c.length) = terminalGradient c γ := by
  simp [blockGradient]

@[simp]
theorem blockGradient_castSucc (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) :
    blockGradient c γ i.castSucc = transitionGradient c γ i := by
  simp [blockGradient]

/-- The single smooth convex objective associated with all block gradients. -/
noncomputable def blockObjective (c : Chain h) (γ : Fin c.length → ℝ) :
    SmoothConvexFn (BlockSpace c) 1 :=
  generatorObjective (blockGradient c γ)

theorem anchor_zero_norm (c : Chain h) (γ : Fin c.length → ℝ) :
    ‖anchor c γ 0‖ = 1 := by
  simp [anchor, axis]

theorem block_dimension_le_horizon (c : Chain h) : c.length + 1 ≤ T + 1 := by
  exact Nat.add_le_add_right c.length_le_horizon 1

/-! ## Projection computations for the block paths -/

theorem axis_inner_axis (c : Chain h) (i j : Fin (c.length + 1)) :
    ⟪axis c i, axis c j⟫_ℝ = if i = j then 1 else 0 := by
  simp [axis, EuclideanSpace.inner_single_left]

/-- The shifted point `q_i(s) - g_i`, parametrized by `u = s + 1`. -/
noncomputable def blockShift (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) (u : ℝ) : BlockSpace c :=
  (coordinateAmplitude c γ i.castSucc / transitionScale c i) •
    ((transitionScale c i - u) • axis c i.castSucc +
      (u * γ i) • axis c i.succ)

/-- The affine path in a nonterminal block. -/
noncomputable def blockPath (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) (s : ℝ) : BlockSpace c :=
  anchor c γ i.castSucc - s • transitionGradient c γ i

theorem blockPath_sub_gradient (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (i : Fin c.length) (s : ℝ) :
    blockPath c γ i s - transitionGradient c γ i = blockShift c γ i (s + 1) := by
  have hH : transitionScale c i ≠ 0 := ne_of_gt (transitionScale_pos c hh i)
  have hanchor : anchor c γ i.castSucc =
      (coordinateAmplitude c γ i.castSucc / transitionScale c i) •
        (transitionScale c i • axis c i.castSucc) := by
    simp only [anchor, smul_smul]
    congr 1
    field_simp [hH]
  rw [blockPath, hanchor]
  simp only [transitionGradient, blockShift]
  module

theorem blockShift_inner_self (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) (u : ℝ) :
    ⟪blockShift c γ i u, transitionGradient c γ i⟫_ℝ =
      coordinateAmplitude c γ i.castSucc ^ 2 / transitionScale c i ^ 2 *
        (transitionScale c i - u * (1 + γ i ^ 2)) := by
  simp only [blockShift, transitionGradient, inner_smul_left, inner_smul_right,
    inner_add_left, inner_sub_right]
  rw [axis_inner_axis, axis_inner_axis, axis_inner_axis, axis_inner_axis]
  simp only [map_div₀, map_sub, map_mul, conj_trivial]
  simp [ne_of_gt i.castSucc_lt_succ, ne_of_lt i.castSucc_lt_succ]
  ring

theorem blockShift_inner_terminal (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) (u : ℝ) :
    ⟪blockShift c γ i u, terminalGradient c γ⟫_ℝ =
      (coordinateAmplitude c γ i.castSucc / transitionScale c i) *
      (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) *
      (if i.succ = Fin.last c.length then u * γ i else 0) := by
  simp only [blockShift, terminalGradient, inner_smul_left, inner_smul_right,
    inner_add_left]
  rw [axis_inner_axis, axis_inner_axis]
  by_cases hi : i.succ = Fin.last c.length
  · simp [hi]
    ring
  · have hi0 : i.castSucc ≠ Fin.last c.length := by
      intro heq
      have hlt := i.castSucc_lt_succ
      rw [heq] at hlt
      exact (not_lt_of_ge (Fin.le_last i.succ)) hlt
    simp [hi, hi0]

theorem blockShift_inner_transition (c : Chain h) (γ : Fin c.length → ℝ)
    (i j : Fin c.length) (u : ℝ) :
    ⟪blockShift c γ i u, transitionGradient c γ j⟫_ℝ =
      (coordinateAmplitude c γ i.castSucc / transitionScale c i) *
      (coordinateAmplitude c γ j.castSucc / transitionScale c j) *
      ((transitionScale c i - u) *
          ((if i.castSucc = j.castSucc then 1 else 0) -
            γ j * (if i.castSucc = j.succ then 1 else 0)) +
       (u * γ i) *
          ((if i.succ = j.castSucc then 1 else 0) -
            γ j * (if i.succ = j.succ then 1 else 0))) := by
  simp only [blockShift, transitionGradient, inner_smul_left, inner_smul_right,
    inner_add_left, inner_sub_right]
  rw [axis_inner_axis, axis_inner_axis, axis_inner_axis, axis_inner_axis]
  simp only [map_div₀, map_sub, map_mul, conj_trivial]
  ring

theorem blockShift_inner_successor (c : Chain h) (γ : Fin c.length → ℝ)
    (i : Fin c.length) (u : ℝ) :
    ⟪blockShift c γ i u, blockGradient c γ i.succ⟫_ℝ =
      coordinateAmplitude c γ i.castSucc ^ 2 * γ i ^ 2 * u /
        (transitionScale c i * nextScale c i) := by
  by_cases hi : i.val + 1 < c.length
  · let j : Fin c.length := ⟨i.val + 1, hi⟩
    have hs : i.succ = j.castSucc := by ext; rfl
    rw [hs, blockGradient_castSucc, blockShift_inner_transition]
    have h00 : i.castSucc ≠ j.castSucc := by
      intro heq
      have hval := congrArg Fin.val heq
      simp [j] at hval
    have h01 : i.castSucc ≠ j.succ := by
      intro heq
      have hval := congrArg Fin.val heq
      simp [j] at hval
      omega
    have hlam : coordinateAmplitude c γ j.castSucc =
        coordinateAmplitude c γ i.castSucc * γ i := by
      rw [← hs]
      exact coordinateAmplitude_succ c γ i
    have hnext : nextScale c i = transitionScale c j := by
      simp [nextScale, hi, j]
    simp [h00, h01, hs, ne_of_lt j.castSucc_lt_succ]
    rw [← hnext, hlam]
    ring
  · have hs : i.succ = Fin.last c.length := by
      ext
      simp
      omega
    rw [hs, blockGradient_last, blockShift_inner_terminal]
    have hlam := coordinateAmplitude_succ c γ i
    rw [hs] at hlam
    have hnext : nextScale c i = c.terminalScale := by
      simp [nextScale, hi]
    simp [hs]
    rw [← hnext, hlam]
    ring

theorem blockShift_inner_self_ge_successor (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : AmplitudesAdmissible c γ) (i : Fin c.length) {u : ℝ}
    (huU : u ≤ c.gapMass i) :
    ⟪blockShift c γ i u, blockGradient c γ i.succ⟫_ℝ ≤
      ⟪blockShift c γ i u, transitionGradient c γ i⟫_ℝ := by
  rw [blockShift_inner_successor, blockShift_inner_self]
  have hH : 0 < transitionScale c i := transitionScale_pos c hh i
  have hN : 0 < nextScale c i := nextScale_pos c hh i
  have hU : 0 < c.gapMass i := c.gapMass_pos hh i
  have hy : 0 < excess h (c.selected i) := c.selected_excess_pos i
  have hHdef : transitionScale c i = c.gapMass i + excess h (c.selected i) := rfl
  have hden : 0 < c.gapMass i * (transitionScale c i + nextScale c i) := by
    positivity
  have hbound := hγ.2 i
  simp only [localAmplitudeBound] at hbound
  have hbound := (le_div_iff₀ hden).mp hbound
  have hG : 0 ≤ γ i ^ 2 := sq_nonneg _
  have hcoef : 0 ≤ nextScale c i * (1 + γ i ^ 2) +
      γ i ^ 2 * transitionScale c i := by positivity
  have hucoef := mul_le_mul_of_nonneg_right huU hcoef
  have hendpoint : c.gapMass i *
        (nextScale c i * (1 + γ i ^ 2) +
          γ i ^ 2 * transitionScale c i) ≤
      nextScale c i * transitionScale c i := by
    calc
      _ = c.gapMass i * nextScale c i +
          γ i ^ 2 * (c.gapMass i *
            (transitionScale c i + nextScale c i)) := by ring
      _ ≤ c.gapMass i * nextScale c i +
          excess h (c.selected i) * nextScale c i :=
        add_le_add (le_refl _) hbound
      _ = nextScale c i * transitionScale c i := by
        rw [hHdef]
        ring
  have hcore : γ i ^ 2 * u * transitionScale c i ≤
      (transitionScale c i - u * (1 + γ i ^ 2)) * nextScale c i := by
    nlinarith
  have hfac : 0 ≤ coordinateAmplitude c γ i.castSucc ^ 2 := sq_nonneg _
  rw [div_eq_mul_inv, div_eq_mul_inv]
  have hleft :
      coordinateAmplitude c γ i.castSucc ^ 2 * γ i ^ 2 * u *
          (transitionScale c i * nextScale c i)⁻¹ =
        coordinateAmplitude c γ i.castSucc ^ 2 *
          (γ i ^ 2 * u * transitionScale c i) /
            (transitionScale c i ^ 2 * nextScale c i) := by
    field_simp
  have hright :
      coordinateAmplitude c γ i.castSucc ^ 2 * (transitionScale c i ^ 2)⁻¹ *
          (transitionScale c i - u * (1 + γ i ^ 2)) =
        coordinateAmplitude c γ i.castSucc ^ 2 *
          ((transitionScale c i - u * (1 + γ i ^ 2)) * nextScale c i) /
            (transitionScale c i ^ 2 * nextScale c i) := by
    field_simp
  rw [hleft, hright]
  exact div_le_div_of_nonneg_right
    (mul_le_mul_of_nonneg_left hcore hfac) (by positivity)

theorem blockShift_inner_successor_nonneg (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (i : Fin c.length) {u : ℝ} (hu : 0 ≤ u) :
    0 ≤ ⟪blockShift c γ i u, blockGradient c γ i.succ⟫_ℝ := by
  rw [blockShift_inner_successor]
  have hH := transitionScale_pos c hh i
  have hN := nextScale_pos c hh i
  positivity

theorem blockShift_inner_self_nonneg (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : AmplitudesAdmissible c γ)
    (i : Fin c.length) {u : ℝ} (hu0 : 0 ≤ u) (huU : u ≤ c.gapMass i) :
    0 ≤ ⟪blockShift c γ i u, transitionGradient c γ i⟫_ℝ :=
  (blockShift_inner_successor_nonneg c γ hh i hu0).trans
    (blockShift_inner_self_ge_successor c γ hh hγ i huU)

theorem blockShift_inner_transition_le_self (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : AmplitudesAdmissible c γ) (i j : Fin c.length) {u : ℝ}
    (hu0 : 0 ≤ u) (huU : u ≤ c.gapMass i) :
    ⟪blockShift c γ i u, transitionGradient c γ j⟫_ℝ ≤
      ⟪blockShift c γ i u, transitionGradient c γ i⟫_ℝ := by
  by_cases hji : j = i
  · subst j
    exact le_rfl
  by_cases hsucc : j.castSucc = i.succ
  · rw [← blockGradient_castSucc c γ j, hsucc]
    exact blockShift_inner_self_ge_successor c γ hh hγ i huU
  by_cases hpred : j.succ = i.castSucc
  · have hii0 : i.castSucc ≠ j.castSucc := by
      intro heq
      apply hji
      exact (Fin.castSucc_inj.mp heq).symm
    have hii1 : i.castSucc = j.succ := hpred.symm
    have his0 : i.succ ≠ j.castSucc := Ne.symm hsucc
    have his1 : i.succ ≠ j.succ := by
      intro heq
      apply hji
      exact (Fin.succ_inj.mp heq).symm
    rw [blockShift_inner_transition]
    rw [if_neg hii0, if_pos hii1, if_neg his0, if_neg his1]
    norm_num only [mul_zero, sub_zero, zero_sub, add_zero]
    have hH := transitionScale_pos c hh i
    have hJ := transitionScale_pos c hh j
    have hli := coordinateAmplitude_pos c γ hγ.1 i.castSucc
    have hlj := coordinateAmplitude_pos c γ hγ.1 j.castSucc
    have hgu := hγ.1 j
    have hHu : 0 ≤ transitionScale c i - u := by
      have hdef : transitionScale c i = c.gapMass i + excess h (c.selected i) := rfl
      have hy := c.selected_excess_pos i
      linarith
    have hAi : 0 ≤ coordinateAmplitude c γ i.castSucc /
        transitionScale c i := (div_pos hli hH).le
    have hAj : 0 ≤ coordinateAmplitude c γ j.castSucc /
        transitionScale c j := (div_pos hlj hJ).le
    have hneg : -(transitionScale c i - u) * γ j ≤ 0 :=
      mul_nonpos_of_nonpos_of_nonneg (neg_nonpos.mpr hHu) hgu.le
    have hnonpos :
        (coordinateAmplitude c γ i.castSucc / transitionScale c i) *
          (coordinateAmplitude c γ j.castSucc / transitionScale c j) *
            (-(transitionScale c i - u) * γ j) ≤ 0 :=
      mul_nonpos_of_nonneg_of_nonpos (mul_nonneg hAi hAj) hneg
    calc
      _ = (coordinateAmplitude c γ i.castSucc / transitionScale c i) *
          (coordinateAmplitude c γ j.castSucc / transitionScale c j) *
            (-(transitionScale c i - u) * γ j) := by ring
      _ ≤ _ := hnonpos.trans (blockShift_inner_self_nonneg c γ hh hγ i hu0 huU)
  · have hii0 : i.castSucc ≠ j.castSucc := by
      intro heq
      apply hji
      exact (Fin.castSucc_inj.mp heq).symm
    have hii1 : i.castSucc ≠ j.succ := Ne.symm hpred
    have his0 : i.succ ≠ j.castSucc := Ne.symm hsucc
    have his1 : i.succ ≠ j.succ := by
      intro heq
      apply hji
      exact (Fin.succ_inj.mp heq).symm
    rw [blockShift_inner_transition]
    rw [if_neg hii0, if_neg hii1, if_neg his0, if_neg his1]
    norm_num
    exact blockShift_inner_self_nonneg c γ hh hγ i hu0 huU

theorem blockShift_inner_terminal_le_self (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : AmplitudesAdmissible c γ) (i : Fin c.length) {u : ℝ}
    (hu0 : 0 ≤ u) (huU : u ≤ c.gapMass i) :
    ⟪blockShift c γ i u, terminalGradient c γ⟫_ℝ ≤
      ⟪blockShift c γ i u, transitionGradient c γ i⟫_ℝ := by
  by_cases hi : i.succ = Fin.last c.length
  · rw [← blockGradient_last c γ, ← hi]
    exact blockShift_inner_self_ge_successor c γ hh hγ i huU
  · rw [blockShift_inner_terminal]
    simp [hi]
    exact blockShift_inner_self_nonneg c γ hh hγ i hu0 huU

theorem blockShift_inner_generator_le_self (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : AmplitudesAdmissible c γ) (i : Fin c.length) {u : ℝ}
    (hu0 : 0 ≤ u) (huU : u ≤ c.gapMass i) (j : Fin (c.length + 1)) :
    ⟪blockShift c γ i u, blockGradient c γ j⟫_ℝ ≤
      ⟪blockShift c γ i u, transitionGradient c γ i⟫_ℝ := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) j
  · rw [blockGradient_last]
    exact blockShift_inner_terminal_le_self c γ hh hγ i hu0 huU
  · rw [blockGradient_castSucc]
    exact blockShift_inner_transition_le_self c γ hh hγ i j hu0 huU

/-- On every nonterminal block path, the intended generator is the projection. -/
theorem blockPath_projection (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : AmplitudesAdmissible c γ)
    (i : Fin c.length) {s : ℝ} (hs0 : 0 ≤ s)
    (hsU : s ≤ ∑ t ∈ c.gapTimes i, h t) :
    convexProj (generatorHull (blockGradient c γ))
      (Set.nonempty_of_mem (zero_mem_generatorHull (blockGradient c γ)))
      (generatorHull_complete (blockGradient c γ))
      (generatorHull_convex (blockGradient c γ)) (blockPath c γ i s) =
        transitionGradient c γ i := by
  rw [← blockGradient_castSucc c γ i]
  apply convexProj_generator_eq (blockGradient c γ) i.castSucc
  · rw [blockGradient_castSucc, blockPath_sub_gradient c γ hh]
    apply blockShift_inner_self_nonneg c γ hh hγ i
    · linarith
    · simp only [Chain.gapMass]
      linarith
  · intro j
    rw [blockGradient_castSucc, blockPath_sub_gradient c γ hh]
    apply blockShift_inner_generator_le_self c γ hh hγ i
    · linarith
    · simp only [Chain.gapMass]
      linarith

/-! The last block has only one active coordinate, so its projection comparison is simpler. -/

noncomputable def terminalTail (c : Chain h) : ℝ :=
  ∑ t ∈ c.gapTimes c.length, h t

noncomputable def terminalPath (c : Chain h) (γ : Fin c.length → ℝ)
    (s : ℝ) : BlockSpace c :=
  anchor c γ (Fin.last c.length) - s • terminalGradient c γ

noncomputable def terminalShift (c : Chain h) (γ : Fin c.length → ℝ)
    (s : ℝ) : BlockSpace c :=
  (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) •
    ((c.terminalScale - s - 1) • axis c (Fin.last c.length))

theorem terminalPath_sub_gradient (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (s : ℝ) :
    terminalPath c γ s - terminalGradient c γ = terminalShift c γ s := by
  have hH : c.terminalScale ≠ 0 := ne_of_gt (c.terminalScale_pos hh)
  have hanchor : anchor c γ (Fin.last c.length) =
      (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) •
        (c.terminalScale • axis c (Fin.last c.length)) := by
    simp only [anchor, smul_smul]
    congr 1
    field_simp [hH]
  simp only [terminalPath]
  rw [hanchor]
  simp only [terminalGradient, terminalShift]
  module

theorem terminalShift_coefficient_nonneg (c : Chain h)
    (hh : IsNonnegativeSchedule h) {s : ℝ} (hs : s ≤ terminalTail c) :
    0 ≤ c.terminalScale - s - 1 := by
  have htail : 0 ≤ terminalTail c := by
    exact Finset.sum_nonneg fun t _ ↦ hh t
  unfold terminalTail at hs htail
  simp only [Chain.terminalScale]
  linarith

theorem terminalShift_inner_self_nonneg (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : ∀ i, 0 < γ i) {s : ℝ} (hs : s ≤ terminalTail c) :
    0 ≤ ⟪terminalShift c γ s, terminalGradient c γ⟫_ℝ := by
  simp only [terminalShift, terminalGradient, inner_smul_left, inner_smul_right]
  rw [axis_inner_axis]
  simp only [map_div₀, map_sub, map_one, conj_trivial]
  have hH := c.terminalScale_pos hh
  have hlam := coordinateAmplitude_pos c γ hγ (Fin.last c.length)
  have hcoef := terminalShift_coefficient_nonneg c hh hs
  positivity

theorem terminalShift_inner_transition (c : Chain h) (γ : Fin c.length → ℝ)
    (j : Fin c.length) (s : ℝ) :
    ⟪terminalShift c γ s, transitionGradient c γ j⟫_ℝ =
      (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) *
      (c.terminalScale - s - 1) *
      (coordinateAmplitude c γ j.castSucc / transitionScale c j) *
      (-γ j * (if Fin.last c.length = j.succ then 1 else 0)) := by
  simp only [terminalShift, transitionGradient, inner_smul_left, inner_smul_right,
    inner_sub_right]
  rw [axis_inner_axis, axis_inner_axis]
  simp only [map_div₀, map_sub, map_one, conj_trivial]
  have hneq : Fin.last c.length ≠ j.castSucc :=
    ne_of_gt (Fin.castSucc_lt_last j)
  simp [hneq]
  split_ifs <;> ring

theorem terminalShift_inner_transition_le_self (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : ∀ i, 0 < γ i) (j : Fin c.length) {s : ℝ}
    (hs : s ≤ terminalTail c) :
    ⟪terminalShift c γ s, transitionGradient c γ j⟫_ℝ ≤
      ⟪terminalShift c γ s, terminalGradient c γ⟫_ℝ := by
  rw [terminalShift_inner_transition]
  have hH := c.terminalScale_pos hh
  have hJ := transitionScale_pos c hh j
  have hlm := coordinateAmplitude_pos c γ hγ (Fin.last c.length)
  have hlj := coordinateAmplitude_pos c γ hγ j.castSucc
  have hcoef := terminalShift_coefficient_nonneg c hh hs
  have hleft :
      (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) *
        (c.terminalScale - s - 1) *
        (coordinateAmplitude c γ j.castSucc / transitionScale c j) ≥ 0 := by
    positivity
  have hright : -γ j * (if Fin.last c.length = j.succ then 1 else 0) ≤ 0 := by
    split_ifs
    · nlinarith [hγ j]
    · simp
  have hnonpos := mul_nonpos_of_nonneg_of_nonpos hleft hright
  exact hnonpos.trans (terminalShift_inner_self_nonneg c γ hh hγ hs)

theorem terminalShift_inner_generator_le_self (c : Chain h)
    (γ : Fin c.length → ℝ) (hh : IsNonnegativeSchedule h)
    (hγ : ∀ i, 0 < γ i) {s : ℝ} (hs : s ≤ terminalTail c)
    (j : Fin (c.length + 1)) :
    ⟪terminalShift c γ s, blockGradient c γ j⟫_ℝ ≤
      ⟪terminalShift c γ s, terminalGradient c γ⟫_ℝ := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) j
  · rw [blockGradient_last]
  · rw [blockGradient_castSucc]
    exact terminalShift_inner_transition_le_self c γ hh hγ j hs

/-- On the terminal block path, the terminal generator is the projection. -/
theorem terminalPath_projection (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : ∀ i, 0 < γ i)
    {s : ℝ} (_hs0 : 0 ≤ s) (hs : s ≤ terminalTail c) :
    convexProj (generatorHull (blockGradient c γ))
      (Set.nonempty_of_mem (zero_mem_generatorHull (blockGradient c γ)))
      (generatorHull_complete (blockGradient c γ))
      (generatorHull_convex (blockGradient c γ)) (terminalPath c γ s) =
        terminalGradient c γ := by
  rw [← blockGradient_last c γ]
  apply convexProj_generator_eq (blockGradient c γ) (Fin.last c.length)
  · rw [blockGradient_last, terminalPath_sub_gradient c γ hh]
    exact terminalShift_inner_self_nonneg c γ hh hγ hs
  · intro j
    rw [blockGradient_last, terminalPath_sub_gradient c γ hh]
    exact terminalShift_inner_generator_le_self c γ hh hγ hs j

/-! ## The chronological timeline -/

/-- Selected transition times strictly before the natural time `n`. -/
noncomputable def selectedBefore (c : Chain h) (n : ℕ) : Finset (Fin T) :=
  c.times.filter fun s ↦ s.val < n

/-- The block containing the iterate at time `t`. -/
noncomputable def currentBlock (c : Chain h) (t : Fin (T + 1)) :
    Fin (c.length + 1) :=
  ⟨(selectedBefore c t.val).card, by
    unfold selectedBefore
    have hc := Finset.card_le_card
      (Finset.filter_subset (fun s : Fin T ↦ s.val < t.val) c.times)
    unfold Chain.length
    omega⟩

theorem currentBlock_succ_val (c : Chain h) (t : Fin T) :
    (currentBlock c t.succ).val = (currentBlock c t.castSucc).val +
      if t ∈ c.times then 1 else 0 := by
  simp only [currentBlock, selectedBefore]
  by_cases ht : t ∈ c.times
  · have heq : c.times.filter (fun s : Fin T ↦ s.val < t.succ.val) =
        insert t (c.times.filter fun s : Fin T ↦ s.val < t.castSucc.val) := by
      ext s
      constructor
      · intro hs
        have hs' := Finset.mem_filter.mp hs
        by_cases hst : s = t
        · exact Finset.mem_insert.mpr (Or.inl hst)
        · apply Finset.mem_insert.mpr
          right
          apply Finset.mem_filter.mpr
          refine ⟨hs'.1, ?_⟩
          have hlt := hs'.2
          change s.val < t.val + 1 at hlt
          change s.val < t.val
          by_contra hnot
          apply hst
          apply Fin.ext
          omega
      · intro hs
        rcases Finset.mem_insert.mp hs with rfl | hs
        · apply Finset.mem_filter.mpr
          exact ⟨ht, by simp⟩
        · have hs' := Finset.mem_filter.mp hs
          apply Finset.mem_filter.mpr
          refine ⟨hs'.1, ?_⟩
          have hlt := hs'.2
          change s.val < t.val at hlt
          change s.val < t.val + 1
          omega
    rw [heq, Finset.card_insert_of_notMem]
    · simp [ht]
    · intro hmem
      have hlt := (Finset.mem_filter.mp hmem).2
      exact (lt_irrefl t.val) hlt
  · have heq : c.times.filter (fun s : Fin T ↦ s.val < t.succ.val) =
        c.times.filter fun s : Fin T ↦ s.val < t.castSucc.val := by
      ext s
      constructor
      · intro hs
        have hs' := Finset.mem_filter.mp hs
        apply Finset.mem_filter.mpr
        refine ⟨hs'.1, ?_⟩
        have hne : s ≠ t := by intro he; subst s; exact ht hs'.1
        have hlt := hs'.2
        change s.val < t.val + 1 at hlt
        change s.val < t.val
        by_contra hnot
        apply hne
        apply Fin.ext
        omega
      · intro hs
        have hs' := Finset.mem_filter.mp hs
        apply Finset.mem_filter.mpr
        refine ⟨hs'.1, ?_⟩
        have hlt := hs'.2
        change s.val < t.val at hlt
        change s.val < t.val + 1
        omega
    rw [heq]
    simp [ht]

theorem selected_eq_orderEmb (c : Chain h) :
    c.selected = c.times.orderEmbOfFin rfl := by
  exact Finset.orderEmbOfFin_unique rfl c.selected_mem c.selected_strictMono

theorem range_selected (c : Chain h) : Set.range c.selected = c.times := by
  rw [selected_eq_orderEmb]
  exact Finset.range_orderEmbOfFin c.times rfl

theorem selectedBefore_selected_card (c : Chain h) (i : Fin c.length) :
    (selectedBefore c (c.selected i).val).card = i.val := by
  have heq : selectedBefore c (c.selected i).val =
      Finset.image c.selected (Finset.Iio i) := by
    ext s
    simp only [selectedBefore, Finset.mem_filter, Finset.mem_image, Finset.mem_Iio]
    constructor
    · intro hs
      have hrange : s ∈ Set.range c.selected := by
        rw [range_selected c]
        exact hs.1
      obtain ⟨j, rfl⟩ := hrange
      exact ⟨j, (c.selected_strictMono.lt_iff_lt).mp hs.2, rfl⟩
    · rintro ⟨j, hji, rfl⟩
      exact ⟨c.selected_mem j, c.selected_strictMono hji⟩
  rw [heq, Finset.card_image_of_injective _ c.selected_injective, Fin.card_Iio]

theorem currentBlock_selected (c : Chain h) (i : Fin c.length) :
    currentBlock c (c.selected i).castSucc = i.castSucc := by
  apply Fin.ext
  exact selectedBefore_selected_card c i

theorem currentBlock_after_selected (c : Chain h) (i : Fin c.length) :
    currentBlock c (c.selected i).succ = i.succ := by
  apply Fin.ext
  rw [currentBlock_succ_val, currentBlock_selected c i]
  simp [c.selected_mem i]

/-- Schedule mass already used within the block containing iterate `t`. -/
noncomputable def blockPrefixMass (c : Chain h) (t : Fin (T + 1)) : ℝ :=
  ∑ s ∈ (c.gapTimes (currentBlock c t).val).filter
      (fun s : Fin T ↦ s.val < t.val), h s

theorem mem_current_gap (c : Chain h) (t : Fin T) (ht : t ∉ c.times) :
    t ∈ c.gapTimes (currentBlock c t.castSucc).val := by
  rw [c.mem_gapTimes_iff]
  exact ⟨ht, rfl⟩

theorem currentBlock_eq_of_not_selected (c : Chain h) (t : Fin T)
    (ht : t ∉ c.times) : currentBlock c t.succ = currentBlock c t.castSucc := by
  apply Fin.ext
  rw [currentBlock_succ_val]
  simp [ht]

theorem blockPrefixMass_succ_of_not_selected (c : Chain h) (t : Fin T)
    (ht : t ∉ c.times) :
    blockPrefixMass c t.succ = blockPrefixMass c t.castSucc + h t := by
  rw [blockPrefixMass, blockPrefixMass, currentBlock_eq_of_not_selected c t ht]
  let k := (currentBlock c t.castSucc).val
  have htgap : t ∈ c.gapTimes k := mem_current_gap c t ht
  have heq : (c.gapTimes k).filter (fun s : Fin T ↦ s.val < t.succ.val) =
      insert t ((c.gapTimes k).filter fun s : Fin T ↦ s.val < t.castSucc.val) := by
    ext s
    constructor
    · intro hs
      have hs' := Finset.mem_filter.mp hs
      by_cases hst : s = t
      · exact Finset.mem_insert.mpr (Or.inl hst)
      · apply Finset.mem_insert.mpr
        right
        apply Finset.mem_filter.mpr
        refine ⟨hs'.1, ?_⟩
        have hlt := hs'.2
        change s.val < t.val + 1 at hlt
        change s.val < t.val
        by_contra hnot
        apply hst
        apply Fin.ext
        omega
    · intro hs
      rcases Finset.mem_insert.mp hs with rfl | hs
      · apply Finset.mem_filter.mpr
        exact ⟨htgap, by simp⟩
      · have hs' := Finset.mem_filter.mp hs
        apply Finset.mem_filter.mpr
        refine ⟨hs'.1, ?_⟩
        have hlt := hs'.2
        change s.val < t.val at hlt
        change s.val < t.val + 1
        omega
  have htbefore : t ∉ (c.gapTimes k).filter
      (fun s : Fin T ↦ s.val < t.castSucc.val) := by
    simp
  rw [heq, Finset.sum_insert htbefore]
  dsimp only [k]
  ring

theorem gapTime_lt_selected (c : Chain h) (i : Fin c.length)
    {s : Fin T} (hs : s ∈ c.gapTimes i) : s < c.selected i := by
  have hsdata := (c.mem_gapTimes_iff i s).mp hs
  by_contra hnot
  have hne : s ≠ c.selected i := by
    intro heq
    subst s
    exact hsdata.1 (c.selected_mem i)
  have hts : c.selected i < s := lt_of_le_of_ne (le_of_not_gt hnot) (Ne.symm hne)
  have hsub : insert (c.selected i) (selectedBefore c (c.selected i).val) ⊆
      selectedBefore c s.val := by
    intro q hq
    rcases Finset.mem_insert.mp hq with rfl | hq
    · apply Finset.mem_filter.mpr
      exact ⟨c.selected_mem i, hts⟩
    · have hq' := Finset.mem_filter.mp hq
      apply Finset.mem_filter.mpr
      exact ⟨hq'.1, lt_trans hq'.2 hts⟩
  have hnotmem : c.selected i ∉ selectedBefore c (c.selected i).val := by
    intro hmem
    exact (lt_irrefl (c.selected i).val) (Finset.mem_filter.mp hmem).2
  have hcard := Finset.card_le_card hsub
  rw [Finset.card_insert_of_notMem hnotmem, selectedBefore_selected_card c i] at hcard
  have hgap : (selectedBefore c s.val).card = i.val := hsdata.2
  rw [hgap] at hcard
  omega

theorem blockPrefixMass_selected (c : Chain h) (i : Fin c.length) :
    blockPrefixMass c (c.selected i).castSucc =
      ∑ s ∈ c.gapTimes i, h s := by
  rw [blockPrefixMass, currentBlock_selected c i]
  congr 1
  apply Finset.filter_eq_self.mpr
  intro s hs
  exact gapTime_lt_selected c i hs

theorem blockPrefixMass_after_selected (c : Chain h) (i : Fin c.length) :
    blockPrefixMass c (c.selected i).succ = 0 := by
  rw [blockPrefixMass, currentBlock_after_selected c i]
  apply Finset.sum_eq_zero
  intro s hs
  exfalso
  have hsfilter := Finset.mem_filter.mp hs
  have hsgap := (c.mem_gapTimes_iff (i.val + 1) s).mp hsfilter.1
  have hsle : s ≤ c.selected i := by
    have hlt := hsfilter.2
    change s.val < (c.selected i).val + 1 at hlt
    exact Fin.le_iff_val_le_val.mpr (by omega)
  have hsne : s ≠ c.selected i := by
    intro heq
    subst s
    exact hsgap.1 (c.selected_mem i)
  have hslt : s < c.selected i := lt_of_le_of_ne hsle hsne
  have hsub : selectedBefore c s.val ⊆ selectedBefore c (c.selected i).val := by
    intro q hq
    have hq' := Finset.mem_filter.mp hq
    apply Finset.mem_filter.mpr
    exact ⟨hq'.1, lt_trans hq'.2 hslt⟩
  have hcard := Finset.card_le_card hsub
  rw [selectedBefore_selected_card c i] at hcard
  have hgap : (selectedBefore c s.val).card = i.val + 1 := hsgap.2
  rw [hgap] at hcard
  omega

theorem blockPrefixMass_nonneg (c : Chain h) (hh : IsNonnegativeSchedule h)
    (t : Fin (T + 1)) : 0 ≤ blockPrefixMass c t := by
  exact Finset.sum_nonneg fun s _ ↦ hh s

theorem blockPrefixMass_le_gap (c : Chain h) (hh : IsNonnegativeSchedule h)
    (t : Fin (T + 1)) :
    blockPrefixMass c t ≤ ∑ s ∈ c.gapTimes (currentBlock c t).val, h s := by
  apply Finset.sum_le_sum_of_subset_of_nonneg
  · exact Finset.filter_subset _ _
  · intro s _ _
    exact hh s

/-- The explicit point at every time on the chronological block path. -/
noncomputable def chainIterate (c : Chain h) (γ : Fin c.length → ℝ)
    (t : Fin (T + 1)) : BlockSpace c :=
  anchor c γ (currentBlock c t) -
    blockPrefixMass c t • blockGradient c γ (currentBlock c t)

theorem blockObjective_grad_chainIterate (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : AmplitudesAdmissible c γ)
    (t : Fin (T + 1)) :
    (blockObjective c γ).grad (chainIterate c γ t) =
      blockGradient c γ (currentBlock c t) := by
  unfold chainIterate
  generalize hk : currentBlock c t = k
  induction k using Fin.lastCases with
  | last =>
      rw [blockGradient_last]
      apply terminalPath_projection c γ hh hγ.1
      · exact blockPrefixMass_nonneg c hh t
      · simpa [terminalTail, hk] using blockPrefixMass_le_gap c hh t
  | cast i =>
      rw [blockGradient_castSucc]
      apply blockPath_projection c γ hh hγ i
      · exact blockPrefixMass_nonneg c hh t
      · simpa [hk] using blockPrefixMass_le_gap c hh t

theorem transition_endpoint (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (i : Fin c.length) :
    anchor c γ i.castSucc - transitionScale c i • transitionGradient c γ i =
      anchor c γ i.succ := by
  simp only [anchor, transitionGradient]
  rw [coordinateAmplitude_succ]
  have hH : transitionScale c i ≠ 0 :=
    ne_of_gt (transitionScale_pos c hh i)
  have hcancel : transitionScale c i *
      (coordinateAmplitude c γ i.castSucc / transitionScale c i) =
      coordinateAmplitude c γ i.castSucc := by
    field_simp
  rw [smul_smul, hcancel]
  module

theorem selected_total_mass (c : Chain h) (i : Fin c.length) :
    blockPrefixMass c (c.selected i).castSucc + h (c.selected i) =
      transitionScale c i := by
  rw [blockPrefixMass_selected]
  rw [c.step_eq_one_add_excess_of_mem (c.selected_mem i)]
  simp only [transitionScale, Chain.gapMass]
  ring

theorem chain_isGDTrajectory (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : AmplitudesAdmissible c γ) :
    IsGDTrajectory (blockObjective c γ).grad h (chainIterate c γ) := by
  intro t
  rw [blockObjective_grad_chainIterate c γ hh hγ t.castSucc]
  by_cases ht : t ∈ c.times
  · have hrange : t ∈ Set.range c.selected := by
      rw [range_selected c]
      exact ht
    obtain ⟨i, rfl⟩ := hrange
    unfold chainIterate
    rw [currentBlock_after_selected, currentBlock_selected]
    rw [blockPrefixMass_after_selected, blockPrefixMass_selected]
    rw [blockGradient_castSucc]
    simp only [zero_smul, sub_zero]
    rw [← transition_endpoint c γ hh i]
    have hmass := selected_total_mass c i
    rw [blockPrefixMass_selected] at hmass
    rw [← hmass]
    module
  · unfold chainIterate
    rw [currentBlock_eq_of_not_selected c t ht]
    rw [blockPrefixMass_succ_of_not_selected c t ht]
    module

@[simp]
theorem currentBlock_zero (c : Chain h) : currentBlock c 0 = 0 := by
  apply Fin.ext
  simp [currentBlock, selectedBefore]

@[simp]
theorem blockPrefixMass_zero (c : Chain h) : blockPrefixMass c 0 = 0 := by
  simp [blockPrefixMass]

theorem chain_initial_norm (c : Chain h) (γ : Fin c.length → ℝ) :
    ‖chainIterate c γ 0‖ = 1 := by
  simp [chainIterate, anchor_zero_norm]

@[simp]
theorem currentBlock_last (c : Chain h) :
    currentBlock c (Fin.last T) = Fin.last c.length := by
  apply Fin.ext
  simp [currentBlock, selectedBefore, Chain.length]

@[simp]
theorem blockPrefixMass_last (c : Chain h) :
    blockPrefixMass c (Fin.last T) = terminalTail c := by
  simp [blockPrefixMass, terminalTail]

theorem chainIterate_last (c : Chain h) (γ : Fin c.length → ℝ) :
    chainIterate c γ (Fin.last T) = terminalPath c γ (terminalTail c) := by
  simp [chainIterate, terminalPath]

/-! ## Terminal value and realization theorems -/

theorem coordinateAmplitude_last (c : Chain h) (γ : Fin c.length → ℝ) :
    coordinateAmplitude c γ (Fin.last c.length) = ∏ i, γ i := by
  unfold coordinateAmplitude
  change (∏ j ∈ Finset.range c.length, amplitudeNat c γ j) = ∏ i, γ i
  rw [← Fin.prod_univ_eq_prod_range (amplitudeNat c γ) c.length]
  apply Finset.prod_congr rfl
  intro i _
  simp [amplitudeNat, i.isLt]

theorem coordinateAmplitude_last_sq (c : Chain h) (γ : Fin c.length → ℝ) :
    coordinateAmplitude c γ (Fin.last c.length) ^ 2 = ∏ i, γ i ^ 2 := by
  rw [coordinateAmplitude_last, Finset.prod_pow]

theorem terminalPath_eq_smul (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (s : ℝ) :
    terminalPath c γ s =
      (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) •
        ((c.terminalScale - s) • axis c (Fin.last c.length)) := by
  have hH : c.terminalScale ≠ 0 := ne_of_gt (c.terminalScale_pos hh)
  have hanchor : anchor c γ (Fin.last c.length) =
      (coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale) •
        (c.terminalScale • axis c (Fin.last c.length)) := by
    simp only [anchor, smul_smul]
    congr 1
    field_simp [hH]
  rw [terminalPath, hanchor]
  simp only [terminalGradient]
  module

theorem terminal_quadraticSupport (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : ∀ i, 0 < γ i) :
    quadraticSupport (terminalGradient c γ) (terminalPath c γ (terminalTail c)) =
      coordinateAmplitude c γ (Fin.last c.length) ^ 2 /
        (2 * c.terminalScale) := by
  rw [terminalPath_eq_smul c γ hh]
  have hH : 0 < c.terminalScale := c.terminalScale_pos hh
  have hlam : 0 < coordinateAmplitude c γ (Fin.last c.length) :=
    coordinateAmplitude_pos c γ hγ (Fin.last c.length)
  have ha : 0 < coordinateAmplitude c γ (Fin.last c.length) / c.terminalScale :=
    div_pos hlam hH
  simp only [quadraticSupport, terminalGradient, inner_smul_left, inner_smul_right,
    norm_smul]
  rw [axis_inner_axis]
  simp only [map_div₀, conj_trivial, Real.norm_eq_abs, abs_of_pos ha]
  have haxis : ‖axis c (Fin.last c.length)‖ = 1 := by simp [axis]
  rw [haxis]
  norm_num
  have hscale : c.terminalScale = 1 + 2 * terminalTail c := rfl
  rw [hscale]
  have hpos : 1 + 2 * terminalTail c ≠ 0 := by linarith
  field_simp [hpos]
  ring

theorem chain_terminal_value (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : AmplitudesAdmissible c γ) :
    blockObjective c γ (chainIterate c γ (Fin.last T)) - blockObjective c γ 0 =
      coordinateAmplitude c γ (Fin.last c.length) ^ 2 /
        (2 * c.terminalScale) := by
  rw [chainIterate_last]
  change projectionEnvelope (generatorHull (blockGradient c γ))
      (Set.nonempty_of_mem (zero_mem_generatorHull (blockGradient c γ)))
      (generatorHull_complete (blockGradient c γ))
      (generatorHull_convex (blockGradient c γ)) (terminalPath c γ (terminalTail c)) -
    projectionEnvelope (generatorHull (blockGradient c γ))
      (Set.nonempty_of_mem (zero_mem_generatorHull (blockGradient c γ)))
      (generatorHull_complete (blockGradient c γ))
      (generatorHull_convex (blockGradient c γ)) 0 = _
  rw [projectionEnvelope_zero _ _ _ _
    (zero_mem_generatorHull (blockGradient c γ)), sub_zero]
  unfold projectionEnvelope
  have htail : 0 ≤ terminalTail c := Finset.sum_nonneg fun t _ ↦ hh t
  have hp := terminalPath_projection c γ hh hγ.1 htail (le_refl (terminalTail c))
  rw [hp]
  exact terminal_quadraticSupport c γ hh hγ.1

/-- Formal version of the manuscript's geometric-realization theorem.  It includes the empty
chain: then `c.length = 0`, the amplitude family is empty, and `BlockSpace c` is one-dimensional. -/
theorem geometricRealization (c : Chain h) (γ : Fin c.length → ℝ)
    (hh : IsNonnegativeSchedule h) (hγ : AmplitudesAdmissible c γ) :
    ∃ (F : SmoothConvexFn (BlockSpace c) 1)
      (x : Fin (T + 1) → BlockSpace c),
      F.minimizer = 0 ∧ ‖x 0‖ = 1 ∧ IsGDTrajectory F.grad h x ∧
        F (x (Fin.last T)) - F 0 =
          (1 / (2 * c.terminalScale)) * ∏ i, γ i ^ 2 := by
  refine ⟨blockObjective c γ, chainIterate c γ, rfl, chain_initial_norm c γ,
    chain_isGDTrajectory c γ hh hγ, ?_⟩
  rw [chain_terminal_value c γ hh hγ, coordinateAmplitude_last_sq]
  ring

@[simp]
theorem transitionScale_eq_nonterminalScale (c : Chain h) (i : Fin c.length) :
    transitionScale c i = c.nonterminalScale i := rfl

theorem nextScale_eq_blockScale_succ (c : Chain h) (i : Fin c.length) :
    nextScale c i = c.blockScale i.succ := by
  by_cases hi : i.val + 1 < c.length
  · let j : Fin c.length := ⟨i.val + 1, hi⟩
    have hs : i.succ = j.castSucc := by ext; rfl
    rw [show nextScale c i = transitionScale c j by simp [nextScale, hi, j]]
    rw [hs, Chain.blockScale_castSucc]
    rfl
  · have hs : i.succ = Fin.last c.length := by
      ext
      simp
      omega
    rw [show nextScale c i = c.terminalScale by simp [nextScale, hi]]
    rw [hs, Chain.blockScale_last]

@[simp]
theorem localAmplitudeBound_eq_localBound (c : Chain h) (i : Fin c.length) :
    localAmplitudeBound c i = c.localBound i := by
  rw [localAmplitudeBound, Chain.localBound]
  rw [nextScale_eq_blockScale_succ]
  simp only [Chain.precedingMass, transitionScale_eq_nonterminalScale,
    Chain.blockScale_castSucc]

/-- Saturate every local projection constraint. -/
noncomputable def saturatedAmplitude (c : Chain h) (i : Fin c.length) : ℝ :=
  Real.sqrt (c.localBound i)

theorem saturatedAmplitude_admissible (c : Chain h) (hh : IsNonnegativeSchedule h) :
    AmplitudesAdmissible c (saturatedAmplitude c) := by
  constructor
  · intro i
    exact Real.sqrt_pos.2 (c.localBound_pos hh i)
  · intro i
    rw [show saturatedAmplitude c i ^ 2 = c.localBound i by
      exact Real.sq_sqrt (c.localBound_pos hh i).le]
    rw [localAmplitudeBound_eq_localBound]

theorem saturatedAmplitude_sq (c : Chain h) (hh : IsNonnegativeSchedule h) :
    ∏ i, saturatedAmplitude c i ^ 2 = ∏ i, c.localBound i := by
  apply Finset.prod_congr rfl
  intro i _
  exact Real.sq_sqrt (c.localBound_pos hh i).le

/-- Realize the value of any chronological chain by one smooth convex GD instance. -/
theorem chainValueRealization (c : Chain h) (hh : IsNonnegativeSchedule h) :
    ∃ (F : SmoothConvexFn (BlockSpace c) 1)
      (x : Fin (T + 1) → BlockSpace c),
      F.minimizer = 0 ∧ ‖x 0‖ = 1 ∧ IsGDTrajectory F.grad h x ∧
        F (x (Fin.last T)) - F 0 = c.value / 2 := by
  obtain ⟨F, x, hmin, hx, htraj, hval⟩ :=
    geometricRealization c (saturatedAmplitude c) hh
      (saturatedAmplitude_admissible c hh)
  refine ⟨F, x, hmin, hx, htraj, ?_⟩
  rw [hval, saturatedAmplitude_sq c hh]
  unfold Chain.value
  ring

section EmptyChain

/-! The empty-chain construction is stated separately.  Besides being an edge case of the
general construction, it is useful as a small, independently checkable realization theorem. -/

/-- The one-dimensional space used by the empty chain. -/
abbrev EmptyBlockSpace := EuclideanSpace ℝ (Fin 1)

/-- The unique coordinate vector in the empty-chain construction. -/
noncomputable def emptyAxis : EmptyBlockSpace :=
  EuclideanSpace.single 0 1

/-- The only generator when no transition time is selected. -/
noncomputable def emptyGradient (h : StepSchedule T) : EmptyBlockSpace :=
  (1 / (Chain.empty h).terminalScale) • emptyAxis

noncomputable def emptyGradientFamily (h : StepSchedule T) : Fin 1 → EmptyBlockSpace :=
  fun _ ↦ emptyGradient h

/-- The projection-envelope objective for the empty chain. -/
noncomputable def emptyObjective (h : StepSchedule T) : SmoothConvexFn EmptyBlockSpace 1 :=
  generatorObjective (emptyGradientFamily h)

/-- The affine path followed while all schedule steps remain in the sole terminal block. -/
noncomputable def emptyPath (h : StepSchedule T) (s : ℝ) : EmptyBlockSpace :=
  emptyAxis - s • emptyGradient h

@[simp]
theorem emptyAxis_inner : ⟪emptyAxis, emptyAxis⟫_ℝ = 1 := by
  simp [emptyAxis]

@[simp]
theorem emptyAxis_norm : ‖emptyAxis‖ = 1 := by
  simp [emptyAxis]

/-- Throughout the empty-chain path, the sole nonzero generator is a Euclidean projection. -/
theorem empty_projection (h : StepSchedule T) (hh : IsNonnegativeSchedule h)
    {s : ℝ} (hs₀ : 0 ≤ s) (hs₁ : s ≤ ∑ t, h t) :
    convexProj (generatorHull (emptyGradientFamily h))
      (Set.nonempty_of_mem (zero_mem_generatorHull (emptyGradientFamily h)))
      (generatorHull_complete (emptyGradientFamily h))
      (generatorHull_convex (emptyGradientFamily h)) (emptyPath h s) =
        emptyGradient h := by
  apply convexProj_generator_eq (emptyGradientFamily h) 0
  · rw [show emptyGradientFamily h 0 = emptyGradient h by rfl]
    have hH : 0 < (Chain.empty h).terminalScale :=
      (Chain.empty h).terminalScale_pos hh
    simp only [emptyPath, emptyGradient, inner_sub_left,
      inner_smul_left, inner_smul_right]
    rw [emptyAxis_inner]
    rw [Chain.terminalScale_empty] at hH ⊢
    norm_num at *
    field_simp
    nlinarith
  · intro j
    fin_cases j
    exact le_rfl

/-- Totalize a finite schedule so that ordinary natural-number prefix sums can be used. -/
noncomputable def scheduleNat (h : StepSchedule T) (j : ℕ) : ℝ :=
  if hj : j < T then h ⟨j, hj⟩ else 0

/-- Schedule mass strictly before time `t`. -/
noncomputable def prefixMass (h : StepSchedule T) (t : Fin (T + 1)) : ℝ :=
  ∑ j ∈ Finset.range t.val, scheduleNat h j

@[simp]
theorem prefixMass_zero (h : StepSchedule T) : prefixMass h 0 = 0 := by
  simp [prefixMass]

theorem prefixMass_succ (h : StepSchedule T) (t : Fin T) :
    prefixMass h t.succ = prefixMass h t.castSucc + h t := by
  simp [prefixMass, Finset.sum_range_succ, scheduleNat, t.isLt]

theorem scheduleNat_nonneg (h : StepSchedule T) (hh : IsNonnegativeSchedule h)
    (j : ℕ) : 0 ≤ scheduleNat h j := by
  unfold scheduleNat
  split_ifs with hj
  · exact hh ⟨j, hj⟩
  · exact le_rfl

theorem total_eq_scheduleNat_sum (h : StepSchedule T) :
    ∑ t, h t = ∑ j ∈ Finset.range T, scheduleNat h j := by
  rw [← Fin.sum_univ_eq_sum_range (scheduleNat h) T]
  apply Finset.sum_congr rfl
  intro i _
  simp [scheduleNat, i.isLt]

theorem prefixMass_nonneg (h : StepSchedule T) (hh : IsNonnegativeSchedule h)
    (t : Fin (T + 1)) : 0 ≤ prefixMass h t := by
  exact Finset.sum_nonneg fun j _ ↦ scheduleNat_nonneg h hh j

theorem prefixMass_le_total (h : StepSchedule T) (hh : IsNonnegativeSchedule h)
    (t : Fin (T + 1)) : prefixMass h t ≤ ∑ j, h j := by
  rw [total_eq_scheduleNat_sum]
  apply Finset.sum_le_sum_of_subset_of_nonneg
  · exact Finset.range_mono (Nat.le_of_lt_succ t.isLt)
  · intro j _ _
    exact scheduleNat_nonneg h hh j

theorem prefixMass_last (h : StepSchedule T) :
    prefixMass h (Fin.last T) = ∑ t, h t := by
  rw [total_eq_scheduleNat_sum]
  rfl

/-- The explicit iterates of the empty-chain hard instance. -/
noncomputable def emptyIterate (h : StepSchedule T) (t : Fin (T + 1)) :
    EmptyBlockSpace :=
  emptyPath h (prefixMass h t)

theorem emptyObjective_grad_iterate (h : StepSchedule T)
    (hh : IsNonnegativeSchedule h) (t : Fin (T + 1)) :
    (emptyObjective h).grad (emptyIterate h t) = emptyGradient h := by
  exact empty_projection h hh (prefixMass_nonneg h hh t) (prefixMass_le_total h hh t)

theorem empty_isGDTrajectory (h : StepSchedule T) (hh : IsNonnegativeSchedule h) :
    IsGDTrajectory (emptyObjective h).grad h (emptyIterate h) := by
  intro t
  rw [emptyObjective_grad_iterate h hh t.castSucc]
  simp only [emptyIterate, emptyPath]
  rw [prefixMass_succ h t]
  module

theorem empty_initial_norm (h : StepSchedule T) : ‖emptyIterate h 0‖ = 1 := by
  simp [emptyIterate, emptyPath]

theorem empty_quadraticSupport_terminal (h : StepSchedule T)
    (hh : IsNonnegativeSchedule h) :
    quadraticSupport (emptyGradient h) (emptyPath h (∑ t, h t)) =
      1 / (2 * (Chain.empty h).terminalScale) := by
  have hH : 0 < (Chain.empty h).terminalScale :=
    (Chain.empty h).terminalScale_pos hh
  have hc : 0 < 1 / (Chain.empty h).terminalScale := one_div_pos.mpr hH
  simp only [quadraticSupport, emptyPath, emptyGradient,
    inner_smul_left, inner_sub_right, inner_smul_right, norm_smul]
  rw [emptyAxis_inner, emptyAxis_norm]
  simp only [map_div₀, map_one, conj_trivial, mul_one,
    Real.norm_eq_abs, abs_of_pos hc]
  rw [Chain.terminalScale_empty] at hH hc ⊢
  norm_num at *
  field_simp
  ring

theorem empty_terminal_value (h : StepSchedule T) (hh : IsNonnegativeSchedule h) :
    emptyObjective h (emptyIterate h (Fin.last T)) - emptyObjective h 0 =
      1 / (2 * (Chain.empty h).terminalScale) := by
  rw [show emptyIterate h (Fin.last T) = emptyPath h (∑ t, h t) by
    simp only [emptyIterate, prefixMass_last]]
  change projectionEnvelope (generatorHull (emptyGradientFamily h))
      (Set.nonempty_of_mem (zero_mem_generatorHull (emptyGradientFamily h)))
      (generatorHull_complete (emptyGradientFamily h))
      (generatorHull_convex (emptyGradientFamily h)) (emptyPath h (∑ t, h t)) -
    projectionEnvelope (generatorHull (emptyGradientFamily h))
      (Set.nonempty_of_mem (zero_mem_generatorHull (emptyGradientFamily h)))
      (generatorHull_complete (emptyGradientFamily h))
      (generatorHull_convex (emptyGradientFamily h)) 0 = _
  rw [projectionEnvelope_zero _ _ _ _
    (zero_mem_generatorHull (emptyGradientFamily h)), sub_zero]
  unfold projectionEnvelope
  rw [empty_projection h hh (Finset.sum_nonneg fun t _ ↦ hh t) le_rfl]
  exact empty_quadraticSupport_terminal h hh

/-- Geometric realization for the edge case in which no transition step is selected. -/
theorem geometricRealization_empty (h : StepSchedule T) (hh : IsNonnegativeSchedule h) :
    ∃ (F : SmoothConvexFn EmptyBlockSpace 1)
      (x : Fin (T + 1) → EmptyBlockSpace),
      F.minimizer = 0 ∧ ‖x 0‖ = 1 ∧ IsGDTrajectory F.grad h x ∧
        F (x (Fin.last T)) - F 0 =
          1 / (2 * (Chain.empty h).terminalScale) := by
  exact ⟨emptyObjective h, emptyIterate h, rfl, empty_initial_norm h,
    empty_isGDTrajectory h hh, empty_terminal_value h hh⟩

end EmptyChain

end ChainScalars

end GDLowerBound.GeometricRealization
